[package]
name = "tinyrasputin"
version = "1.1.0"
authors = ["Jengamon <bob.hostern@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.2.1"
clap = "2.33.0"
rand = "0.7"
rand_distr = "0.2"