[package]
name = "tinyrasputin"
version = "1.5.0"
authors = ["Jengamon <bob.hostern@gmail.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "^1.2"
rand = "^0.7"
itertools = "^0.8"
approx = "^0.3"
