name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache cargo files
      uses: actions/cache@v1
      id: cache
      with:
        path: ~/.cargo
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
    - name: Install just
      if: steps.cache.outputs.cache-hit != 'true'
      run: cargo install just
    - name: Setup environment
      run: just env && just mode=release env
    - name: Build
      run: just package-build
    - name: Run tests
      run: just package-test
    - name: Build release package
      run: just mode=release package
    - name: Upload release package
      uses: actions/upload-artifact@v1
      with:
        name: release-build
        path: tinyrasputin-release.zip