name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup
      run: cargo install just && just env
    - name: Build
      run: just package-build
    - name: Run tests
      run: just package-test
